### PR TITLE
Merge upstream LevelDB 1.20

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
@tmagik I had to delete and recreate this repository in order to fix up the missing "Forked from" marker above (which made PRs complicated). I didn't mean to delete your comments on the earlier version of this PR, but perhaps they're more appropriate as a separate issue (here, or on the https://github.com/bitcoin/bitcoin/ repo)?

**Comment by tmagik** [comment]
Ah that’s what happened. The relevant comments can be condensed to:

@sipa so maybe for bitcoin core, then what I'd propose is:

-  if -core keeps bitcoin-consensus-leveldb in the same build tree, that it at least be provided as a separate library, with libbitcoin-leveldb and libbitcoin-memenv available for other projects
-  develop a testing system and risk mitigation strategy by which we can gain some confidence that alternative database backends (such as maybe hyperleveldb or rocksdb) work correctly

**Comment by sipa** [comment]
@tmagik Those are comments that belong in an issue on https://github.com/bitcoin/bitcoin/.

**Comment by theuni** [comment]
optimized crc32 is exciting, IIRC that's a pretty significant bottleneck.

<cfields_> sipa: for leveldb merge, whenever it's needed: https://github.com/theuni/bitcoin/commit/2cb7dda13884e44105f33c16e7e2c1a9aed46295

**Comment by gmaxwell** [comment]
ACK. (tested previously)

**Pull request merged**
